[tox]
envlist =
  py{27,310,311,312,313,314}-core
  py{27}-django{111}
  py{310,311,312,313,314}-django{42,50,51,52}
  py{312,313,314}-django{60}

[testenv]
usedevelop = True
commands =
  core: python -m pytest test
  django{111}: django-admin.py test -v2 django_tests {env:D_ARGS:}
  django{42,50,51,52,60}: django-admin test -v2 django_tests {env:D_ARGS:}
passenv = *
deps =
  pytest
  py27: mock
  django111: Django>=1.11,<1.12
  django42: Django>=4.2,<4.3
  django50: Django>=5.0,<5.1
  django51: Django>=5.1,<5.2
  django52: Django>=5.2,<5.3
  django60: Django>=6.0,<6.1
setenv =
  DJANGO_SETTINGS_MODULE=django_tests.settings
