# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tests', '0002_remove_poll_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='image_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='image_width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
