name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04  # focal equivalent

    strategy:
      matrix:
        include:
          - python-version: "2.7"
            toxenv: py27-core
          - python-version: "3.9"
            toxenv: py39-core
          - python-version: "3.10"
            toxenv: py310-core
          - python-version: "3.11"
            toxenv: py311-core
          - python-version: "3.12"
            toxenv: py312-core
          - python-version: "3.13"
            toxenv: py313-core
          - python-version: "2.7"
            toxenv: py27-django111
          - python-version: "3.9"
            toxenv: py39-django32
          - python-version: "3.10"
            toxenv: py310-django42
          - python-version: "3.11"
            toxenv: py311-django42
          - python-version: "3.12"
            toxenv: py312-django50
          - python-version: "3.13"
            toxenv: py313-django51

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        if: matrix.python-version != '2.7'
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python 2.7 manually
        if: matrix.python-version == '2.7'
        run: |
          sudo apt-get update
          sudo apt-get install -y python2.7 python2.7-dev python2.7-distutils curl
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
          sudo python2.7 get-pip.py
          python2.7 --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox pytest

      - name: Set CLOUDINARY_URL
        run: |
          export CLOUDINARY_URL=$(bash tools/get_test_cloud.sh)
          echo "cloud_name: $(echo $CLOUDINARY_URL | cut -d'@' -f2)"
          echo "CLOUDINARY_URL=$CLOUDINARY_URL" >> $GITHUB_ENV

      - name: Run tests
        env:
          TOXENV: ${{ matrix.toxenv }}
          PYTHONPATH: ${{ github.workspace }}
        run: tox -e $TOXENV
