name: Cloudinary Python SDK Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - python-version: 2.7
            toxenv: py27-core
          - python-version: 3.9
            toxenv: py39-core
          - python-version: 3.10
            toxenv: py310-core
          - python-version: 3.11
            toxenv: py311-core
          - python-version: 3.12
            toxenv: py312-core
          - python-version: 3.13
            toxenv: py313-core
          - python-version: 2.7
            toxenv: py27-django111
          - python-version: 3.9
            toxenv: py39-django32
          - python-version: 3.10
            toxenv: py310-django42
          - python-version: 3.11
            toxenv: py311-django42
          - python-version: 3.12
            toxenv: py312-django50
          - python-version: 3.13
            toxenv: py313-django51
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install tox pytest mock

      - name: Run tests with tox
        env:
          TOXENV: ${{ matrix.toxenv }}
          DJANGO_SETTINGS_MODULE: django_tests.settings
        run: tox -e $TOXENV
